### ISSUE TITLE
Initializer 

### ISSUE THREAD

**Issue by rocketbop** [Skalar/ember-cli-cordova-shims#5]
Is it still necessary to add an event listener for push notification in an Ember initializer if I use Cordova Shims? Also, would you mind sharing what your initializer looks like in general when building Cordova and Ember? :)

**Comment by theodorton** [comment]
There is an example on how to use Push Notifications in the README. Creating a service in an initializer, as described there, should be sufficient. The event listeners that are documented in PushPlugin's README will be created by the service.

Check out the README and let me know if anything should be more clearly documented :)

**Comment by rocketbop** [comment]
Cool will do, thanks!
